apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-music-deployment
  labels:
    app: storage-music
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-music

  template:
    metadata:
      name: storage-music
      labels:
        app: storage-music
    spec:
      containers:
        - image: storage-stream-music
          name: storage-music
          imagePullPolicy: Never
          resources: {}
          ports:
            - containerPort: 80
