apiVersion: v1
kind: Service
metadata:
  name: storage-music-service
  labels:
    run: storage-music
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: storage-music
  type: NodePort
